# Copyright 2022 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

__defaults__(
    dict(
        python_source=dict(resolve="pants-2.26"),
    )
)
