on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python 3.11.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Initialize Pants launcher
        uses: pantsbuild/actions/init-pants@56efcdb79721bc7726edf542e324468033e4e21c
        with:
          # cache0 makes it easy to bust the cache if needed
          gha-cache-key: cache0-py3.11
          named-caches-hash: ${{ hashFiles('3rdparty/python/pants-2.26.lock') }}
      - name: Lint and typecheck the code
        run: "pants lint check ::"
      - name: Run tests
        run: "pants test ::"
